#!/opt/pwn.college/bash

ARGS="$@"
exec /usr/bin/env -u SHLVL /challenge/chio.py --parent shellscript --check_env 298:dydburpsva --empty_env --check_arg 114:fzfndxwllz --reward /flag -- run ${ARGS[@]}