#!/opt/pwn.college/bash

ARGS="$@"
exec /usr/bin/env -u SHLVL /challenge/chio.py --parent shellscript --check_env 312:nhiccfjlkp --empty_env --check_arg 308:lxdlgfouwn --reward /flag -- run ${ARGS[@]}