#!/opt/pwn.college/bash

ARGS="$@"
exec /usr/bin/env -u SHLVL /challenge/chio.py --parent shellscript --check_env 291:fnjflognjr --empty_env --check_arg 173:qotcxgzrjr --reward /flag -- run ${ARGS[@]}