#!/usr/bin/env exec-suid -- /bin/python3 -I

import sys


def reverse_string(s):
    return s[::-1]


def encode_to_bits(s):
    return b"".join(format(c, "08b").encode("latin1") for c in s)


print("Enter the password:")
entered_password = sys.stdin.buffer.read1()
correct_password = b"\x0f&\xdd\x8d3\xf0\x1c\xe5"

print(f"Read {len(entered_password)} bytes.")


correct_password = correct_password.hex().encode("l1")
correct_password = correct_password[::-1]
correct_password = encode_to_bits(correct_password)
correct_password = correct_password.hex().encode("l1")


if entered_password == correct_password:
    print("Congrats! Here is your flag:")
    print(open("/flag").read().strip())
else:
    print("Incorrect!")
    sys.exit(1)
