#!/opt/pwn.college/bash

ARGS="$@"
exec /usr/bin/env -u SHLVL /challenge/chio.py --parent shellscript --check_stdin_pipe cat --check_stdout_pipe cat --num_challenges 50 --challenge_ops +*&^%| --challenge_depth 5 --reward /flag -- $0 ${ARGS[@]}