#!/opt/pwn.college/bash

ARGS="$@"
exec /usr/bin/env -u SHLVL /challenge/chio.py --client python --listen_dup 1758 --num_challenges 5 --challenge_ops +*% --challenge_depth 3 --reward /flag -- $0 ${ARGS[@]}