#!/opt/pwn.college/bash

ARGS="$@"
exec /usr/bin/env -u SHLVL /challenge/chio.py --client shellscript --listen_dup 1946 --num_challenges 5 --challenge_ops +*% --challenge_depth 3 --reward /flag -- $0 ${ARGS[@]}