#!/opt/pwn.college/bash

ARGS="$@"
exec /challenge/chio.py --parent shellscript --check_stdin_pipe cat --check_stdout_pipe cat --num_challenges 50 --challenge_ops +*&^%| --challenge_depth 5 --reward /flag -- run ${ARGS[@]}