#!/opt/pwn.college/bash

ARGS="$@"
exec /usr/bin/env -u SHLVL /challenge/chio.py --parent shellscript --check_env 206:stcyvpmzck --empty_env --check_arg 212:iejnxlxihr --reward /flag -- run ${ARGS[@]}