#!/usr/bin/exec-suid -- /bin/python3 -I

import sys


def reverse_string(s):
    return s[::-1]


print("Enter the password:")
entered_password = sys.stdin.buffer.read1()
correct_password = b"\x17x\xee5\xd4\x08D\xbd"

print(f"Read {len(entered_password)} bytes.")


correct_password = correct_password.hex().encode("l1")
correct_password = correct_password[::-1]
correct_password = correct_password[::-1]
correct_password = correct_password.hex().encode("l1")


if entered_password == correct_password:
    print("Congrats! Here is your flag:")
    print(open("/flag").read().strip())
else:
    print("Incorrect!")
    sys.exit(1)
