#!/opt/pwn.college/bash

ARGS="$@"
exec /usr/bin/env -u SHLVL /challenge/chio.py --parent shellscript --check_env 186:legqxjzokz --empty_env --check_arg 283:kufdgztfre --reward /flag -- run ${ARGS[@]}