#!/opt/pwn.college/bash

ARGS="$@"
exec /challenge/chio.py --parent shellscript --check_stdin_fifo --check_stdout_fifo --num_challenges 1 --challenge_ops +* --challenge_depth 1 --reward /flag -- run ${ARGS[@]}