#!/opt/pwn.college/bash

ARGS="$@"
exec /usr/bin/env -u SHLVL /challenge/chio.py --parent shellscript --check_env 219:ccfvtrmbcp --empty_env --check_arg 103:sgskpeyliz --reward /flag -- run ${ARGS[@]}