#!/opt/pwn.college/bash

ARGS="$@"
exec /usr/bin/env -u SHLVL /challenge/chio.py --client binary --listen_dup 1821 --num_challenges 5 --challenge_ops +*% --challenge_depth 3 --reward /flag -- run ${ARGS[@]}